Blog/Controllers/PostController.cs
using Blog.Models;
using BlogBusinessLogic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Controllers
{
    public class PostController : Controller
    {
        BlogManager blogManager = new BlogManager();
        // GET: Post
        public ActionResult Index()
        {
            var posts = blogManager.GetPost().Select(post =>
            new PostViewModel
            {
                Author = post.Author,
                Content = post.Content,
                ID = post.ID,
                CreateDate = post.CreateDate,
                Title = post.Title,
                ModifyDate = post.ModifyDate,
            }).ToList();
            var postListViewModel = new PostListViewModel()
            {
                Posts = posts,
                Count = posts.Count,
                PageCount = 1,
                Pages = 1
            };
            return View(postListViewModel);
        }
        public ActionResult Get(int id)
        {
            var post = blogManager.GetPostByID(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            var postViewModel = new PostViewModel()
            {
                Author = post.Author,
                Content = post.Content,
                CreateDate = post.CreateDate,
                ID = post.ID,
                Title = post.Title,
                ModifyDate = post.ModifyDate,
            };
            return View(postViewModel);
        }

    }
}

Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 小神的博客</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("小神的博客", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("博客", "Index", "Post")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系我们", "Contact", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (!this.Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("登录", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                        <li>@Html.ActionLink("注册新用户", "Register", "Account", routeValues: null, htmlAttributes: new { id = "reggisterLink" })</li>
                    }
                    else
                    {
                        <li class="li"><span>欢迎 @this.User.Identity.Name</span></li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 小神的博客</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>