Blog/Areas/Admin/Controllers/PostManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Blog.Areas.Admin.Models;
using BlogModel;
using BlogBusinessLogic;

namespace Blog.Areas.Admin.Controllers
{
    public class PostManagerController : Controller
    {
        BlogManager blogManager = new BlogManager();
        // GET: Admin/PostManager
        public ActionResult Index()
        {
            var posts = blogManager.GetPost().Select(i => new PostMaintainViewModel
            {
                ID = i.ID,
                Content = i.Content,
                Title = i.Title,
            }).ToList();

            PostMaintainListViewModel postMaintainListViewModel = new PostMaintainListViewModel()
            {
                Posts = posts,
                Count = posts.Count,
                PageCount = 1,
                Pages = 1,
            };
            return View(postMaintainListViewModel);
        }
        public ActionResult Update(int id)
        {
            var post = blogManager.GetPostByID(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            PostMaintainViewModel postMaintainView = new PostMaintainViewModel
            {
                ID = post.ID,
                Title = post.Title,
                Content = post.Content,
            };
            return View(postMaintainView);
        }
        [HttpPost]
        public ActionResult Update(PostMaintainViewModel postMaintainView)
        {
            var post = blogManager.GetPostByID(postMaintainView.ID);
            if (post == null)
            {
                return HttpNotFound();
            }
            post.Title = postMaintainView.Title;
            post.Content = postMaintainView.Content;
            blogManager.Update(post);
            return RedirectToAction("Index");
        }
        public ActionResult Insert()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Insert(PostMaintainViewModel postMaintainView)
        {
            Post post = new Post()
            {
                Title = postMaintainView.Title,
                Content = postMaintainView.Content,
                CreateDate = DateTime.Now,
                ModifyDate = DateTime.Now,
                Author = "小贤",
                IsPublish = true,
            };
            blogManager.Insert(post);
            return RedirectToAction("Index");
        }
    }
}

Blog/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 小神的博客管理</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("小神的博客", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("博客管理", "Index", "PostManager")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系我们", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 小神的博客</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>